### ISSUE TITLE
Docs 0.9.2

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1024]
## Breaking Changes

- [x] Update to .Net 5
- [x] Removed `ModalSize.None`
- [x] `<Divider>` property `Type` renamed to `DividerType?`
- [x] ChartOptions renamed
  - `AxeTicks` to `AxisTicks`
  - `AxeGridLines` to `AxisGridLines`
  - `AxeScaleLabel` to `AxisScaleLabel`
  - `AxeMinorTick` to `AxisMinorTick`
  - `AxeMajorTick` to `AxisMajorTick`
- [x] #1147 Property unification and custom input sizes
- [x] #1227 Generic Typing for SelectList bound value

## Features

- [x] #841 RichTextEdit based on QuillJS
- [x] #1042 Vertical Bar Improvements (part 1)
- [x] #1271 Added the possibility to change the page size and the position of the pager.
- [x] #1371 Reinitialize EditContext on Validations
- [x] #1266 Link button

### Optimizations

- [ ] #1115 Delay the text entered in TextEdit when ChangeTextOnKeyPress is true
- [ ] #663 Add color for Switch component

### DataGrid

- [ ] Add `PageButtonTemplate `
- [ ] Add `CaptionTemplate` to column header
- [ ] `NewItemDefaultSetter` for new items
- [ ] `PopupColumnSize` for sizing edit fields
- [ ] `PopupSize` for sizing edit dialog
- [x] #601 Validation on DataGridColumn
- [x] #306 Validation in datagrid
- [ ] #1106 DataGrid access to FilteredData

### Others

- [ ] #917 Allow Popup Size to be Set for DataGrid edit/new Modals
- [ ] #918 DataGrid. Title property for modal dialog
- [ ] #1064 DataGrid component editing mode needs to be customized
- [x] #1061 Alert visibility two-way binding
- [ ] #1023 Add `Stacked` to chart options
- [ ] #929 Theme Color Alpha
- [ ] #870 DividerType in Theme DividerOptions
- [x] #934 DataGrid: Define default value for input on RowInserting
- [x] #949 Overriding NewCommand button in Grid
- [x] #998 Refactor the TextChanged mode for TextEdit and NumericEdit to be configured for each instance
- [x] #982 Is it possible to put an image in the datagrid Header instead of a string for the caption? similar to the newcommand in the datagridcommandcolumn.
- [x] #1089 Layout Improvements
- [x] #1084 Whole layout overlay
- [x] #663 Switch Component needs Color Property
- [ ] #1204 Implement custom Check for Bulma provider
- [ ] #1212 Implemented store on ListGroup and fixed Clicked event on ListGroupItem
- [x] #1205 Add Disabled property to Dropdown
- [x] #1179 Autocomplete - add local ChangeTextOnKeyPress property
- [x] #1177 Add Reset() method to FileEdit
- [ ] #900 Size Helpers
- [ ] #1087 Typography unification
- [ ] #1243 Handle OnFocus Events on Inputs
- [ ] #1152 Pop-Up Menu Width property in Vertical Bar
- [x] #1329 Added StatusChanged event to Validation component
- [ ] #1343 Chart Ability To Remove And Set Data On Datasets
- [x] #967 DataGrid - Is it possible to force single-column sorting
- [x] #1000 DataGrid TextAlignment does not affect caption
- [x] #1390 BarLink Still Ignores Attributes
- [ ] #983 Add multiline labels support for ChartJS component
- [ ] #1129 Expose ColumnType in the Columns property of DataGridReadDataEventArgs

## Bug Fixes

- [ ] #1065 Bootstrap ModalContent generating invalid class name
- [ ] #1043 Bar component : BarEnd is not pushed on right side if there's no BarStart Element in BarMenu
- [ ] #1011 Text-Alignment on DataGridCommandColumn seems not to work
- [ ] #893 ColorEdit not aligned with horizontal label
- [ ] #1008 Chart : still some references to `Axe`
- [ ] #952 FileEdit does not show filename(s) after browsing
- [ ] #1081 Addons with Select component not working for AntDesign
- [ ] #857 Datagrid pager
- [ ] #1069 The LayoutFooter component is not pinned to the bottom of the window
- [ ] #1038 Sidebar under header
- [x] #1053 TextEdit jump caret to the end of the text for every typed char, when ChangeTextOnKeyPress is true
- [ ] #1120 Material and eFrolic tab buttons don't change cursor
- [x] #1149 Bug: DecimalsSeparator of NumericEdit does not affect Value
- [ ] #1203 In DataGrid DisplayFormat disappears when Editing Inline
- [ ] #1185 ListGroupItem Clicked event is not working
- [ ] #1183 RadioGroup CheckedValue property change is not handled
- [ ] #1262 Default column classname needs to be removed in some cases
- [ ] #1264 Fixed ListGroup selecting mode
- [ ] #1093 Problem with vertical BarItem longer text
- [ ] #1091 Bar expand/collapse not working on mobile devices
- [ ] #1223 DataGridColumn Displayable="false" shows column in DataGridEditMode.Inline edit mode
- [ ] #1249 Non-displayable DataGridColumns are displayed when editing
- [ ] #1092 Bar default vertical scrollbar in Firefox and Edge
- [ ] #1114 BarDropdown is not working in Bulma
- [ ] #1180 BarDropdownToggle component hover/click does not work over chevron icon
- [ ] #1332 BarLink Ignores Attributes
- [ ] #1335 DateEdit ignores readonly attribute
- [ ] #1384 nav-pills & nav-tabs should not be using together
- [ ] #758 Optimize demo apps for mobile
- [ ] #1433 BarDropdownItem Ignores Target
- [ ] #1441 DataGrid pagination does not working
- [ ] #1450 Validation issue in Blazorise 0.9.2 rc-2
- [ ] #1461 Fixed row un-selection

## PRs

#1022 Fix Convertor.ToDictionary for Arrays and Lists
#1023 Add `Stacked` to Axis options
#1055 Option to hide the toggle icon in a dropdown
#1070 DataGrid. Title property for modal dialog
#1071 DataGrid Popup sizing
#1077 DataGrid default value setter for new items
#1085 Add CaptionTemplate to DataGrid column header
#1090 Layout Improvements
#1082 Fix and extend data grid paging
#1098 Fix: Resolved Bar issue relating to recent Layout Improvements
#1097 Add color for switches
#1110 Adding somekind of lazy loading to the tree view
#1130 Page button documentation
#1161 Fix typo in ThemeContainerMaxWidthOptions
#1163 Fix typo in ValidBreakpoints and ValidContainerMaxWidths
#1159 Removed duplicate Info badge and pill from demo page
#1132 DataGrid validations
#1176 Add VisibleCharacters to NumericEdit (#1210)
#941 RichTextEdit based on QuillJS
#1227 Generic Typing for SelectList bound value
#1269 Remove a validation from the parent validation set when it is disposed (@Dedac and @peterlentine)
#1235 Ant design select component improvements
#1252 Adds focus events for all inputs
#1311 Vertical Bar fixes
#1279 Added support for DateTimeOffset conversions
#1302 Added 'Disabled' and 'Clicked'-attributes to Tab.md docs
#1297 Update Slider value when dragged by mouse
#1303 Fix RadioGroup bindings
#1325 Fix for Displayable column in inline edit mode
#1271 Added the possibility to change the page size and the position of the pager.
# 1344 Add SetData on BaseChart
#1356 Added sort mode to data grid
#1357 TextAlign also for the table header of data grid
#1375 fix bad author names in nuget package
