### ISSUE TITLE
Fixes for 0.9.1

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1028]
## 0.9.1.2

Changes

PRs

- [x] #1051 Fix problems with empty and loading template

## 0.9.1.1

Changes

- [x] #1026 Bar issue with Server-Side pre-rendering
- [x] #1030 Role="TextRole.Email" cashes Validation
- [x] #1044 Autocomplete, define the type="search" of TextEdit
- [x] #1045 Bootstrap 4.5.0 - ColumnSize="ColumnSize.Is12.OnMobile" still use 'col-xs-12' (deprecated)

PRs

- [x] #1032 Fixes for DataGrid manual data read behavior
- [x] #1027 fix: Server-Side pre-rendering issue with Bar calling JSInterop
