### ISSUE TITLE
Vertical Bar Improvements (part 1)

### ISSUE THREAD

**Issue by MitchellNZ** [stsrki/Blazorise#1042]
Improvements for Vertical Bar modes:

Bugs:
- [x] Toggle button breaks on mobile
- [x] Horizontal Bar expand/collapse not working (see #1091) 
- [x] Bar `100vh;` causes scroll bar in Firefox and Edge (pre-chromium) (see #1092)
- [x] Problem with vertical BarItem longer text (see #1093)
- [x] When you click on item on popup menu, the menu should close. Now it stays open and you need to click outside of it to close it
- [x] When the screen is too short, `VerticalSmall` Bar dropdown menus create an extra scroll bar (even when hidden)
- [x] BarDropdown is not working in Bulma (see #1114)
- [x] `BarIcon` does not work with attributes correctly (such as `Display`, `Class`, `Style`)
- [x] `BarDropdownMenu` popup customisable width in `ThemeBarOptions` (see #1152)
- [x] `BarDropdownToggle` component hover/click does not work over chevron (see #1180)

Features:
- [x] `BarToggler` support 
- [x] Support for multi-level `BarDropdownMenu` (this works for inline, but not small or popout)
- [x] Add bar height (for top bar) to `ThemeProvider`

Documentation:
- [x] Documentation for `BarToggler`
- [x] Documentation for nested `BarDropdownMenus`
- [ ] Documentation for `BarHeight` (horizontal bar)
- [x] Summary comments in code for new parameters (e.g. `Bar` parameter for `BarToggler`, etc)

**Comment by stsrki** [comment]
![image](https://user-images.githubusercontent.com/900302/86060348-d4541e80-ba64-11ea-91bc-d1831af17c1a.png)

**Comment by MitchellNZ** [comment]
_Note for self:_

> When` the screen is too short, VerticalSmall Bar dropdown menus create an extra scroll bar (even when hidden)

This is partially fixed.
Can be fully fixed after #1137

**Comment by MitchellNZ** [comment]
_Note for self:_

>  Support for multi-level BarDropdownMenu

Currently only supported 1 nested level of dropdown.
Will follow this up after 0.9.2.

**Comment by MitchellNZ** [comment]
Issues outstanding after PR part 1 (#1287)

- [ ] AntDesign `BarToggler` fixes (including CSS)
- [ ] AntDesign nested `BarDropdownMenus`
- [ ] Probably some other AntDesign stuff I have missed...
- [ ] Documentation for `BarToggler`
- [ ] Documentation for nested `BarDropdownMenus`
- [ ] Documentation for `BarHeight` (horizontal bar)
- [ ] Summary comments in code for new parameters (e.g. Bar parameter for `BarToggler`)
