### ISSUE TITLE
Layout Improvements

### ISSUE THREAD

**Issue by MitchellNZ** [stsrki/Blazorise#1089]
Improvements for Layout components:

- [x] Support header bar on top of vertical bar (see #1038 for more details)
- [x] Loading `Layout` overlay (see #1084)
- [x] `LayoutFooter` component options for Fixed or always bottom (see #1069)
