### ISSUE TITLE
Docs 0.9.3

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1472]
## Breaking changes

- Implemented `IComponentActivator`
- Support .Net 5 only
- `UseBootstrapProviders` and similar methods not needed anymore
- TValue added to `Autocomplete` component
- TValue added to `DropdownList` component
- `SnackbarAction` button must be placed inside of `SnackbarBody`
- Push methods replaced with PushAsync for `SnackbarStack`
- Restructure files and components
- Update to latest Bulma (0.9.1)
- Removed ModalBackdrop
- `RadioGroup`: `bool Inline` parameter replaced with enum `Orientation`

## Features

- [x] #1542 **Blazorise.Animate** extension
- [x] #1562 **Repeater component**
- [x] #1623 **PageProgress component**
- [x] #1769 **Text input debouncer optimizations**
- [ ] #791 Define ElementId on a component
- [x] #1455 Step component
- [ ] #1464 Provide new object/objectFactory for DataGrid
- [x] #1491 TValue added to Autocomplete component
- [x] #1475 TValue added to DropdownList component
- [ ] #1488 BarIcon IconStyle
- [ ] #852 Add model to EditTemplate context
- [x] #1418 DataGrid: Multiple selection support
- [x] #1482 Snackbar and SnackbarStack improvements
- [x] #1490 Mixed Charts
- [ ] #1530 Autofocus for input components
- [ ] #1550 Created animations for modals and dropdowns
- [x] #1467 Support indeterminate property of the checkbox
- [x] #1244 Add progress indicators
- [ ] #1600 ChartModels missing label property
- [ ] #1621 Datagrid SelectedRow default background color
- [ ] #1583 Add PageSizeChanged to DataGrid
- [ ] #1630 Better background color for tooltip opacity
- [ ] #1198 Support "disabled" DropdownItem
- [ ] #791 IDGenerator is converted from static class to DI interface
- [x] #1445 Allow translation for elements with text
- [x] #1710 SelectList doesn't contain MaxVisibleItems
- [ ] #1326 Add TabIndex to all input components
- [ ] #1681 Add OpenReadStream to FileEntry
- [ ] #1734 Clicked event isn't firing if `BarLink` has property `To` set
- [ ] #1732 DataGrid: trigger ReadData mode externally
- [x] #995 Feature request: Integrate/support FluentValidation
- [ ] #996 Fire EditContext.OnFieldChanged
- [ ] #1746 DateEdit TValue should be used for setting Min and Max values as well
- [ ] #1767 Add InputMode Parameter To the DateEdit
- [ ] #1591 Refactor stores into records
- [ ] #1801 Table drag and drop events
- [ ] #1224 RadioGroup vertical mode
- [ ] #951 Theme options for Radio/RadioGroup
- [ ] #1350 AutoComplete validation works off text rather than value
- [ ] #437 Autocomplete show textvalue after selectchange
- [x] #393 Resizeable columns (drag-to-resize) in DataGrid.
- [ ] #1777 DataGrid Check All - indeterminate state
- [ ] #1803 TreeView: SelectedClass

## Bug Fixes

- [ ] #1378 Bar toggle all text gets highlighted on multiple clicks
- [ ] #874 MemoEdit does not have Feedback Validation Error
- [ ] #1173 Material Progress Bar Percentage Indicator formatting
- [ ] #1572 Page selector does not work and is disappeared on demo sites
- [ ] #1595 Datagrid validation messages only show on second click of save
- [ ] #1402 Empty TextEdit is Null instead of Empty String
- [ ] #1575 Bulma has problem with popup edit mode
- [ ] #1609 Datagrid regression from 0.9.2.2 to 0.9.2.3 onwards
- [ ] #1668 DataGrid TotalItems(short)Template should be marked as parameter
- [ ] #1657 DropdownItem should put the mouse pointer to "hand icon"
- [ ] #1655 Direction of Dropdown
- [ ] #1675 Dropdown stays behind of datagrid container
- [ ] #1731 DataGridColumn TItem Field does not support inherited interface types
- [ ] #1720 Investigate why duplicate FilterContext are used
- [ ] #1029 Bound DateEdit resets when date typed
- [ ] #1515 DateEdit control does not accept a typed year when using binding and DataAnnotations validation
- [ ] #1736 'form-control' class appended twice for Components that inherit BaseTextInput
- [ ] #1762 AutoComplete SelectedValue Conversion Error
- [ ] #1766 Dropdown Selected Element on Dark Colors
- [ ] #1788 DataGrid problems with nested fields
- [ ] #1737 NumericEdit with Min=2
- [ ] #1790 All StateHasChanged should be with InvokeAsync
- [ ] #1780 Preview4 to Preview8: Invalid URI: The hostname could not be parsed.
- [ ] #1711 DataGridColumn Width Property does not render correctly
- [ ] #877 Scrolling long modal - only Firefox
- [ ] #1813 Primary Color Not Changing for Hero
- [ ] #1293 Autocomplete - Selection list does not close
- [ ] #1296 Autocomplete - If no matches are found, a small empty dropdown is shown.
- [ ] #1458 First Element in Chart grey on the hower
- [ ] #1835 Blazorise.BarDropdownToggle: JavaScript interop calls cannot be issued during server-side prerendering
- [ ] #1849 BarDropdownItem padding
- [ ] #1195 DividerType in Theme.DividerOptions not working
- [ ] #1856 RichTextEdit - Toolbar Option - Image
- [ ] #1861 RichTextEdit - Link and image popups might be partly behind the sidebar
- [ ] #1859 Multi-select in DataGrid checkbox does not uncheck if row selected
- [ ] #1582 Something wrong with the layout when using the addon with the navbar
- [ ] #1870 Carousel Indicators z-index higher than Fixed Layout Header.
- [ ] #1617 Using Bar (vertical), first render as Visible = false
- [ ] #1882 Validation is still being called when Disabled=true
- [ ] #1883 Datagrid: Is Async missing?
- [ ] #773 Tabs and TabsContent scenario
- [ ] #1752 RichTextEdit collapses at async initialization
- [ ] #1928 DataGrid - Resize triggers sort
- [ ] #1100 Select component doesn't recognize changes by code
- [ ] #1944 Snackbar seems broken in version 0.9.3

## PRs

- [ ] #1471 Stop text highlighting on vertical bar
- [ ] #1477 NewItemCreator parameter added to DataGrid
- [ ] #1465 Add model to EditTemplate context
- [ ] #1478 DataGrid multiselection
- [ ] #1547 Datagrid multiselection docs
- [ ] #1526 Chart : Update argument from AddLabelsDatasetsAndUpdate to support object (multi-line labels)
- [ ] #1567 Repeater component
- [ ] #1525 LoadingTemplate RenderFragment for buttons
- [ ] #1570 DataGrid: EmptyCellTemplate
- [ ] #1612 Added events EditorFocus and EditorBlur for RichTextEdit
- [ ] #1579 Add PageSizeChanged to DataGrid
- [ ] #1639 Datagrid: fix page selector
- [ ] #1662 DataGrid: fix double ReadData
- [ ] #1677 Add parameter attributes to template properties datagrid
- [ ] #1648 Multiselect inlineedit bugfix
- [ ] #1719 Clear Filter Bug Fix: Filter Template usage
- [ ] #1718 Material DateEdit - Years and Month selectable
- [ ] #1673 Minor improvement to EditContextValidator
- [ ] #1725 SnackbarStack selecting the notification life interval when calling the Push method
- [ ] #1729 Dutch localized resources added
- [ ] #1694 Add OpenReadStream for IFileEntry and FileEdit
- [ ] #1735 BarLink clicked event fired
- [ ] #1580 **Datagrid: ButtonRow**
- [ ] #1754 Add chart data/label Shift and Pop
- [ ] #1789 DataGrid: fix problem with nested fields
- [ ] #1793 Portuguese localized resources added
- [ ] #1805 Improved DataGrid Localization for de-DE
- [ ] #1806 Text localizer fallback to neutral culture
- [ ] #1702 Close Alerts and Modals if CloseButton is within them
- [ ] #1860 RichTextEdit - Add missing actions
- [ ] #1867 RichTextEdit - Catch exception when try to destroy editor in Server side blazor after user closes window.
- [ ] #1863 RTE - Tooltips might (partly) disappear behind sidebar
- [ ] #1865 MultiSelect: Fix checkbox uncheck and multiselectall uncheck, should unselect 'SelectedRow'
- [ ] #1880 DataGrid column DisplayOrder
- [ ] #1886 Datagrid: Introduced async / await on missing events. Introduced a Cancellation Token to issue a cancellation on page changed / page size changed
- [ ] #1889 DataGrid: Just making sure page handler events are unsubscribed.
- [ ] #1885 Datagrid resizable feature
- [ ] #1891 Data grid check all indeterminate state
- [ ] #1896 Datagrid multi selection fixes
- [ ] #1881 RTE - Queue requests for after render and support for content updates
- [ ] #1909 Datagrid: Resize Mode: Header / Columns
- [ ] #1905 RTE - Fix custom config and add docs + example
- [ ] #1916 BaseAfterRenderComponent Null Bug Fix
- [ ] #1918 Datagrid: Is pager visible when button row is on and grid is Empty with an EmptyTemplate set
- [ ] #1930 Datagrid Resize : Ignore clicks from resizer triggering sort or other click events.
- [ ] #1932 TreeView Selected Class: Added Selected Node Class
- [ ] #1935 Add EditOrder to DataGridColumn
- [ ] #1937 DataGrid - Added SortDirectionTemplate to Column
- [ ] #1927 Datagrid: Multi selection improvements
