### ISSUE TITLE
Fixes for 0.9.2

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#1487]
## 0.9.2.5

- [x] #1597 FileEdit not removing file names after reset()
- [x] #1665 Set e.ErrorText don't update ValidationError message
- [x] #1609 Datagrid regression from 0.9.2.2 to 0.9.2.3 onwards
- [x] #1674 Not able to change primary text color

## 0.9.2.4

- [x] #1362 CellsEditableOnEditCommand and CellsEditableOnNewCommand not working in DataGrid EditMode="DataGridEditMode.Popup"
- [x] #1568 DataGrid: CellsEditableOn* properties are not used in EditMode.Popup
- [x] #1581 Fixed CellsEditableOn for popup edit mode. (@paulosdfigueiredo)
- [x] #1571 RadioGroup validation display issue
- [x] #1587 Cards within field are displaced since 0.9.2.3

## 0.9.2.3

- [x] #1548 Blazorise emitting multiple col classes for fields
- [x] #1541 RadioGroup Validation not working as expected
- [x] #1231 Validation is not working for RadioGroup
- [x] #1564 Validation error not shown after more than one failed validator
- [x] #1558 DataGrid PageSize Item changed without reloading the datasource

## 0.9.2.2

- [x] #1508 Validation NullReference Exception
- [x] #1516 Command no longer called upon clicking a button
- [x] #1523 RichTextEdit - Add missing link action (@njannink)
- [x] #1414 Problems with RichTextEdit -> #1524 

## 0.9.2.1

- [x] #1473 Antdesign bugs on v0.9.2
- [x] #1469 Updating TextEdit Pattern and triggering a revalidation doesn't have any effect.
- [x] #1495 0.9.2 Breaking Change: Validation.Validate() now requires a parameter
