### ISSUE TITLE
Documentation for 0.8.5

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#257]
## Breaking changes

- [x] #258 Upgrade to 3.0.0-preview9.19457.4

## Enhancements

- [x] #191 Optimize classname builders
- [x] #145 Using 'enter' as a keypress for SimpleButton
- [x] #252 SelectEdit : Handling for No-Match
- [x] #167 Chart Events Support
- [x] #225 Add missing sub-component to Figure
- [x] #226 Feature Request : `<ValidationNone></ValidationNone>`

## Bug Fixes

- [x] #244 Dropdown going out of bounds
- [x] #162 Snackbar not closing (Server-side)
- [x] #248 launchSettings.json warning
- [x] #222 Validations.ClearAll() Fails to clear validations for second field
- [x] #230 NumericEdit Decimals Property Handling
