### ISSUE TITLE
Docs for 0.8.7

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#312]
### Features

- [x] Refactoring input fields
- [x] #120 Data Annotations Validator support
- [x] #236 Attributes splattering for all components
- [x] #236 `VisibleCharacters` attribute on `TextEdit`
- [x] #234 Control over Edit and New command on DataGrid
  - [x] Renamed `AllowEdit` to `Editable`, `AllowSort` to `Sortable` and `AllowFilter` to `Filterable` on DataGrid
  - [x] Ability to handle the editing of cell values by `CellsEditableOnNewCommand` and `CellsEditableOnEditCommand`
  - [x] Ability to handle visibility of command buttons by `NewCommandAllowed`, `EditCommandAllowed`, etc.
  - [x] ability to control row select state

## Bug fixes

- [x] #251 SelectedEdit : Two-way Binding issue
- [x] #263 Tooltips
- [x] #290 DataGridCommandColumn.Width not working
- [x] #295 Remove lock from CreateDotNetObjectRef
- [x] #342 SelectEdit int valued items ignores 0 when IsMultiple is true
- [x] #320 Validation not updating after reference is changed
- [x] #285 Autocomplete 
- [x] #267 DataGridNumericColumn does not sort numerically

## Usage

- [x] #120 Data Anotations Validator support

## Contributors

- [x] #311 Chart Options Not Updating @andrewwilkin 
- [x] #310 Fix so that Autocomplete dropdown doesn't show empty dropdown @robalexclark
- [x] #347 Font Awesome icon styles @WillianGruber
- [x] #299 Remove unused classes @cassioesp
