### ISSUE TITLE
Docs for 0.8.8

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#469]
## Breaking changes

- [x] #478 Refactor DataGrid PageChanged event
- [x] #441 RowInserting and RowUpdating event handlers

## Features

- [x] #477 DataGrid loading for large data-source
- [x] #345 Control Gradient Colors in Theme generator
- [x] #343 Better support for icons styles
- [x] #446 Support for character casing
- [x] #332 Added Focus() for input components
- [x] #481 How to specify text alignment

## Fixes

- [x] #433 Modal default button for ENTER
- [x] #328 Implement Skip().Take() on DataGrid
- [x] #296 DataGrid no longer scrolls after Popup
- [x] #352 BarBrand theme color
- [x] #368 Outlined Button Color after click
- [x] #337 Fixed IsRounded in theme generator
- [x] #346 Checkbox component color (material)
- [x] #357 Snackbar Location offset
- [x] #307 Tooltip on Button in ButtonGroup breaks ButtonGroup
- [x] #326 RowRemoved EventCallback still called if RowRemoving Action is cancelled
- [x] #344 ModalBody with MaxHeight vertical scroll position is not reset on 2nd show
- [x] #360 NumericEdit not working with @bind-Value
- [x] #300 Autocomplete not calling SelectedValueChanged
- [x] #471 Alert Close Button
- [x] #329 Better handling of DataGrid pagination links
