### ISSUE TITLE
Docs for 0.9.0

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#618]
## Breaking changes

- [x] #4 Rename boolean properties
- [x] #586 Properties renaming
- [x] #305 SelectEdit renamed to Select
- [x] #502 Remove NullableCheckedChanged from CheckEdit
- [x] #682 Rename CheckEdit to Check
- [x] #303 Removed `ColumnSize` from input components
- [x] #630 DateEdit converted to generic component

### Breaking changes as part of new AntDesign 

- [x] Tabs now don't require `TabsContent` to work
- [x] `Field` also must be inside of `Validation`

## New Components

- [x] #284 Live Charts (don't forget to edit NuGet link from release notes page)
- [x] #362 Divider
- [x] #363 Switch
- [x] #594 Radio
- [x] #364 Slider
- [x] #367 FileUpload
- [x] #534 Link
- [x] #700 Layout
- [x] #365 TimeEdit
- [x] #366 ColorEdit

## Features & Fixes

- [x] #612 Make BaseAutocomplete.CurrentSearch
- [x] #358 Snackbar colors and theme support
- [x] #576 Snackbar Closed event
- [x] #570 DataGrid events converted to `EventCallback`
- [x] #296 Cleaned Tabs API
- [x] #549 `CloseReason` for closable components like Modal
- [x] #493 DataGrid multi sorting
- [x] #539 DataGrid sorting icon
- [x] #509 Limit NumericEdit max and min based on it's value type
- [x] #516 DataGrid prev and next templates
- [x] #506 Support for MVVM with ICommand
- [x] #617 DataGrid Row click events
- [x] #681 Some Components can not be styled
- [x] #656 FileUpload does not allow ValidationErrors to be displayed
- [x] #668 Navigation marked as obsolete
- [x] #492 [DataGrid] Add First and Last pagination buttons
- [x] #529 DataGrid styling
- [x] #527 [DataGrid] OnSaveCommand not working when Data is used with EF
- [x] #633 DataGridColumn Filter Template (PR #639)
- [x] #491 [DataGrid] Add Alignment to column
- [x] #490 [DataGrid] Add Format attribute to DataGridColumn
- [x] #569 [Bug] Scroll problem with sidebar
- [x] #662 Possible memory leak on Dispose
- [x] #657 Size-attribute conflict in `<Select>` component
- [x] #394 Custom filtering for DataGrid
- [x] #489 [DataGrid] Aggregate columns
- [x] #722 `.b-body-layout` is not working Bulma
- [x] #571 Prevent users from injecting their own components
- [x] #677 Slider component not initializing as expected with values over 100 (#727)
- [x] #351 Automatically set Breadcrumb active state based on navigation url
- [x] #605 Option to control data-grid column visibility in display mode
- [x] #627 DataGrid Filter box placement #742
- [x] #575 Adding `@attributes` to Blazorise.Components such as SelectList
- [x] #514 [Clean] CascadingParameter access modifiers
- [x] #522 [Refactor] Convert all components to partial classes
- [x] #424 Tabs documentation doesn't match Tabs Demo (documentation solution doesn't work)
- [x] #521 [Clean] DropdownToggle and BarDropdownToggle
- [x] #507 BootStrap Alert Close Button
- [x] #259 Tab not work with blazor preview 9
- [x] #744 Feature Request: Ability to disable tabs

## Other

- [x] #649 Icon page

## PRs

#623 Use Tab key for Autocomplete selection
#685 Grid/Row Gutter
#639  DataGridColumn Filter Template
#699 Fixed minor issues in RadioGroup tests so that they pass
#702 Refactoring the Tests folder into Tests & Demos
#703 Layout additions and fixes
#713 fix: add back sticky header & scrollable sidebar
#727 Fix slider initial value ignoring max
#615 Add DisplayGridColumns parameter (#730)
#726 Added DateEdit tests
#736 [AntDesign] fix: ant card image/cover
#737 [AntDesign] fix: progress bar
#742 fix: insert empty cell when DataGridColumn Filterable is False
#688 Updated contributing doc to include steps to setup development and testing environment.
#719 Added unit test project for Blazorise
#748 fix: Ant Desgin TableRowHeader
#749 refactor: Collapse component away from Card dependency
#752 docs: small changes & added grid docs

**Comment by marcinjakubowski** [comment]
Is there a list of top-level components that are still undocumented? I didn't find docs for Icon anywhere for example (unless I missed it somewhere), maybe it would be a good idea to add them to the list.

**Comment by stsrki** [comment]
@marcinjakubowski Added to the list. tnx

**Comment by Flearz** [comment]
Woaw, well done with the live chart, that's exactly what I asked for, that's awesome. Continue your work you amazing! Good luck.
