### ISSUE TITLE
Docs 0.9.1

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#761]
## Breaking Changes

- [x] #436 DataGrid: Change color of selected row
- [x] #672 Dropdown and DropdownMenu have a IsRightAligned property
- [x] #955 Remove Visibility property
- [x] #961 ChartOptions : Scales object has typo in "Axe"

## New Components

- [x] #645 Carousel
- [x] #767 Jumbotron
- [x] Vertical Bar

## Cleaning & Refactoring

- [x] #771 Delete unused components
- [x] #869 Cascading stores instead of separate properties

## Features

- [x] #758 Optimize demo apps for mobile
- [x] #760 Upgrade Bootstrap provider
- [x] #658 Add validation support to work similar to ValidationSummary.
- [x] #567 Implement Bar Color as a specific parameter in BarThemeOptions
- [x] #763 Option to make vertical Bar
- [x] #766 Toggle Animation not working with Bar component
- [x] #281 Add ability to display close button on badge
- [x] #350 Sidebar width and Bar height
- [x] #369 Button text colors for success and info
- [x] #407 Datagrid mobile friendly
- [x] #413 Button colors
- [x] #412 Error when using SelectEdit with dictionary in DataGrid
- [x] #430 Modal Footer Buttons do not follow theme
- [x] #447 DetailRowTemplate - Remove empty td or change size
- [x] #483 Scroll not working after NavigationManager navigation
- [x] #564 How should these theme attributes be filled?
- [x] #672 Dropdown and DropdownMenu have a RightAligned property
- [x] #676 Add a SetFocus method
- [x] #693 ChartOptions improvement
- [x] #708 Add Display utilities
- [x] #660 Theme options to define layout grid breakpoints
- [x] #790 Figure is not responsive
- [x] #834 Default colors for AntDesign
- [x] #851 Expose EditContext as an attribute of Validations
- [x] #792 error with charts after redrawing
- [x] #847 Modal scrolls to top of 
- [ ] #955 Remove Visibility property

## Bug Fixes

- [x] #622 [DataGrid] [Material] Issue with DetailRowTemplate in Editable DataGrid
- [x] #664 Switch Component Cursor Property doesn't work
- [x] #646 Theme ColorOptions Primary also changes breadcrumb link color
- [x] #686 Null reference exception when DataGridColumn Field is not set
- [x] #661 Auto Validation: Form Validation, error message is displayed on first load.
- [x] #871 Sidebar not colapsing on media breakpoints
- [x] #875 Streaming charts - howto assign specific "datastreams" to specific datasets
- [x] #898 Column Width in Material
- [x] #923 Don't call JSRunner during prerendering
- [x] #655 Memo cursor jumps to end when enclosed in a field and Text is bound
- [x] #733 TextEdit jump caret to the end of the text for every typed char
- [x] #946 Unhandled Exception behavior in UI events
- [x] #961 ChartOptions : Scales object has typo in "Axe"

## PRs

- #785 fix: layout issue for responsive design
- #896 datagriddetail columnspan fix
- #928 Check if component is rendered before calling JSRunner in Dispose()
- #947 Add flask icon to Font Awesome
- #948 DataGrid aggregate column shift fix
- #958 Add ChartColor.FromHtmlColorCode() method
- #968 EmptyTemplate and LoadingTemplate
- #962 Add CardDeck
- #987 TreeView component extension
- #985 ChartJS : convert Options object to Dictionary to fix null values issue
