### ISSUE TITLE
Option to make vertical Bar

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#763]
Refactor Bar component so it can be used as a sidebar.

Linked issue: #567 

@MitchellNZ I'm assigning this to you as you already plan to work on it.

**Comment by MitchellNZ** [comment]
Other PRs I will try look into as part of this:
- [ ] #6 Refactor Sidebar project
- [ ] #190 smaller side bar
- [ ] #350 Sidebar width and Bar height (**possibly**)
- [ ] #567 Implement Bar Color as a specific parameter in BarThemeOptions
- [ ] #766 Toggle Animation not working with Bar component

**Comment by stsrki** [comment]
Sidebar refactor could be too much to handle but if you can pull it off it would be great.

**Comment by stsrki** [comment]
@MitchellNZ  I will close this one. For any issue still left just create separate ticket(s).
