### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stsrki** [stsrki/Blazorise#88]
_Starting from **0.8.1** and up to **0.9** I will try to refactor some parts of Blazorise to clean the code from the design decisions introduced in the past. Since a lot of times Blazor didn't have some features I had to workaround a lot of stuff. So generally this is the time to clean the code. There will be just a minor upgrades to the existing components and bug fixing based on the reports from developers. After 0.9 the main focus will be for **1.0** but only after the **Blazor** exits from **preview** and not too soon._

This is a tracking item for the overall Blazorise features

Items are arranged by milestones.

## v0.7.3

- [x]  #44 Optimize components rendering

## v0.7.4

- [x] #82 Create new DropdownList component
- [x] #89 Create new SelectList component
- [x] #81 Create new Autocomplete component
- [x] Update documentation

## v0.7.5

- [x] #72 Better support for vertical tabs
- [x] #96 Fix: SelectEdit - First Value is null
- [x] #97 Nullable CheckEdit value

## v0.7.6

- [x] #103 Spinner not showing for SimpleButton

## v0.7.7

- [x] #108 Upgrade to Blazor preview 6

## v0.7.8

- [x] #22 Optimize rendering performance for custom-registered components
- [x] #112 Style-Property on CheckEdit
- [x] #119 Convert events to new format
- [x] - #125 Prevent modal from closing

## v0.8

- [x] #101 Theme provider
- [x] #129 Rename Theme enum to ThemeContrast
- [x] #30 Mask for TextEdit, NumberEdit and DateEdit
- [x] #128 New Grid component
- [x] #127 New Accordion component
- [x] #156 .Net core 3 preview 7 support

## v0.8.1

- [x] #165 Nested fields for DataGrid columns
- [x] #149 CardTitle "Size" property ignored
- [x] #148 Add animation options for charts
- [x] #142 Empty the SelectedValue of Autocomplete
- [x] #115 Wrong color filling of Charts for Server-Side Blazor

## v0.8.2

- [x] #188 Selection not working for `SelectEdit` component
- [x] #184 Support for master/detail DataGrid
- [x] #157 Dynamic Sidebar
- [x] #95 Fix Icon component
- [x] #178 Reorganize components

## v0.8.3

- [x] #204 DataGrid Styling
- [x] #204 DataGrid behavior
- [x] #204 DataGrid popup edit mode
- [x] #204 DataGrid command templates
- [x] #113 New Tooltip component
- [x] #8 Components tags should be case sensitive
- [x] #169 Filter methods on DataGrid

## v0.8.4

_This release is going to be just an upgrade to new Blazor p9 since it's going to be released on September 4th. So moving all other task to the next version!_

- [x] #233 Upgrade to Blazor preview 9

## v0.8.5

- [x] #191 Optimize classname builders
- [x] #226 Add `ValidationNone` state
- [x] #225 Add missing sub-component for `Figure`
- [x] #167 Add events to Chart
- [x] #145 Enter key for submit button

## v0.9

- [ ] #163 Implement Ant Design provider

## Backlog

Items here are arranged in rough priority order before they are assigned to the actual release number.

- [ ] #177 Predefined themes
- [ ] #104 Toast component
- [ ] #36 Expand list of icons
- [ ] #4 Rename Boolean attributes
- [ ] #234 Control read-only state on DataGrid edit modes
- [ ] #246 Integrate validation events into Form component

## Planning & Long term

#6 Refactor Sidebar project
#99 Add screen-reader support
#100 Implement missing card-image types
#94 Implement Fabric Core
